export enum USER_VERIFY_STATUS {
  UNVERIFIED = 'UNVERIFIED',
  VERIFIED = 'VERIFIED'
}

export enum ACCESS_SCOPE {
  EVERYONE = 'EVERYONE',
  CONTACTS = 'CONTACTS',
  NOBODY = 'NOBODY'
}

export enum OTP_PURPOSE {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  NEW_DEVICE_LOGIN = 'NEW_DEVICE_LOGIN',
  TWO_FACTOR_AUTHENTICATION = 'TWO_FACTOR_AUTHENTICATION'
}

export enum OTP_STATUS {
  VALID = 'VALID',
  INVALID = 'INVALID',
  EXPIRED = 'EXPIRED'
}

export enum TOKEN_TYPE {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  FORGOT_PASSWORD_TOKEN = 'FORGOT_PASSWORD_TOKEN'
}

export enum FRIEND_REQUEST_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED'
}

export enum NOTIFICATION_TYPE {
  LIKE = 'LIKE',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  MENTION = 'MENTION',
  NEW_COMMENT = 'NEW_COMMENT',
  NEW_MESSAGE = 'NEW_MESSAGE'
}

export enum PROVIDER_TYPE {
  CREDENTIALS = 'CREDENTIALS',
  GOOGLE = 'GOOGLE',
  GITHUB = 'GITHUB'
}

export enum CHAT_TYPE {
  PRIVATE = 'PRIVATE',
  GROUP = 'GROUP'
}

export enum MESSAGE_STATUS {
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  SEEN = 'SEEN'
}

export enum MEDIA_TYPE {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  FILE = 'FILE'
}

export enum MESSAGE_TYPE {
  MEDIA = 'MEDIA',
  TEXT = 'TEXT',
  SYSTEM = 'SYSTEM'
}
