enum SOCKET_EVENTS {
  // CHAT & MESSAGE
  SEND_MESSAGE = 'SEND_MESSAGE',
  RECEIVE_MESSAGE = 'RECEIVE_MESSAGE',
  TYPING = 'TYPING',
  TYPING_START = 'TYPING_START',
  TYPING_STOP = 'TYPING_STOP',
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  MARK_AS_READ = 'MARK_AS_READ',
  MESSAGE_READ = 'MESSAGE_READ',
  
  // REACTIONS
  ADD_REACTION = 'ADD_REACTION',
  REMOVE_REACTION = 'REMOVE_REACTION',
  MESSAGE_REACTION_UPDATED = 'MESSAGE_REACTION_UPDATED',

  // FRIEND REQUESTS
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',

  // NOTIFICATIONS
  NOTIFICATION_NEW = 'NOTIFICATION_NEW',

  // USER STATUS
  USER_ONLINE = 'USER_ONLINE',
  USER_OFFLINE = 'USER_OFFLINE',
  CHECK_ONLINE = 'CHECK_ONLINE',

  // ERROR
  ERROR = 'ERROR',

  // ROOM
  JOIN_ROOM = 'JOIN_ROOM'
}

export default SOCKET_EVENTS
