enum SOCKET_EVENTS {
  // CHAT & MESSAGE
  SEND_MESSAGE = 'SEND_MESSAGE',
  RECEIVE_MESSAGE = 'RECEIVE_MESSAGE',
  TYPING = 'TYPING',
  TYPING_START = 'TYPING_START',
  TYPING_STOP = 'TYPING_STOP',
  NEW_CONVERSATION = 'NEW_CONVERSATION',

  // FRIEND REQUESTS
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',

  // NOTIFICATIONS
  NOTIFICATION_NEW = 'NOTIFICATION_NEW',

  // ERROR
  ERROR = 'ERROR'
}

export default SOCKET_EVENTS
