enum SOCKET_EVENTS {
  // CHAT & MESSAGE
  SEND_MESSAGE = 'SEND_MESSAGE',
  RECEIVE_MESSAGE = 'RECEIVE_MESSAGE',
  TYPING = 'TYPING',
  TYPING_START = 'TYPING_START',
  TYPING_STOP = 'TYPING_STOP',
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  MARK_AS_READ = 'MARK_AS_READ',
  MESSAGE_READ = 'MESSAGE_READ',
  MESSAGE_DELETED = 'MESSAGE_DELETED',
  MESSAGE_UPDATED = 'MESSAGE_UPDATED',
  MESSAGE_PINNED = 'MESSAGE_PINNED',

  // REACTIONS
  ADD_REACTION = 'ADD_REACTION',
  REMOVE_REACTION = 'REMOVE_REACTION',
  MESSAGE_REACTION_UPDATED = 'MESSAGE_REACTION_UPDATED',

  // FRIEND REQUESTS
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',

  // NOTIFICATIONS
  NOTIFICATION_NEW = 'NOTIFICATION_NEW',

  // USER STATUS
  USER_ONLINE = 'USER_ONLINE',
  USER_OFFLINE = 'USER_OFFLINE',
  CHECK_ONLINE = 'CHECK_ONLINE',

  // ERROR
  ERROR = 'ERROR',

  // ROOM
  JOIN_ROOM = 'JOIN_ROOM',

  // CONVERSATION
  CONVERSATION_DELETED = 'CONVERSATION_DELETED',
  GROUP_CREATED = 'GROUP_CREATED',
  NEW_MEMBER = 'NEW_MEMBER',
  JOIN_REQUEST = 'JOIN_REQUEST',
  JOIN_REQUEST_APPROVED = 'JOIN_REQUEST_APPROVED',
  JOIN_REQUEST_REJECTED = 'JOIN_REQUEST_REJECTED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  OWNERSHIP_TRANSFERRED = 'OWNERSHIP_TRANSFERRED',
  MEMBER_ROLE_UPDATED = 'MEMBER_ROLE_UPDATED',
  GROUP_DISBANDED = 'GROUP_DISBANDED',
  GROUP_UPDATED = 'GROUP_UPDATED',
  NEW_JOIN_REQUEST = 'NEW_JOIN_REQUEST',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBERS_ADDED = 'MEMBERS_ADDED',
  JOIN_REQUEST_RECEIVED = 'JOIN_REQUEST_RECEIVED',

  // Thêm các sự kiện mới cho mute/unmute và cài đặt nhóm
  MEMBER_MUTED = 'MEMBER_MUTED',
  MEMBER_UNMUTED = 'MEMBER_UNMUTED',
  GROUP_SETTINGS_UPDATED = 'GROUP_SETTINGS_UPDATED',
  DELETE_MESSAGE = 'DELETE_MESSAGE',

  // CALL EVENTS
  CALL_INITIATED = 'CALL_INITIATED',
  CALL_ACCEPTED = 'CALL_ACCEPTED',
  CALL_REJECTED = 'CALL_REJECTED',
  CALL_ENDED = 'CALL_ENDED',
  CALL_MISSED = 'CALL_MISSED',
  TOGGLE_AUDIO = 'TOGGLE_AUDIO',
  TOGGLE_VIDEO = 'TOGGLE_VIDEO',
  ICE_CANDIDATE = 'ICE_CANDIDATE',
  SDP_OFFER = 'SDP_OFFER',
  SDP_ANSWER = 'SDP_ANSWER'
}

export default SOCKET_EVENTS
